# Config file for automatic testing at travis-ci.org
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
install:
  - pip install tox-travis
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
